version: 2.1

executors:
  golang:
    docker:
      - image: circleci/golang:1.15
jobs:
  test:
    executor: golang
    steps:
      - checkout
      - run:
          name: test
          command: |
            go env -w GOPRIVATE=github.com/line/*
            git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
            make test
  lint:
    executor: golang
    steps:
      - checkout
      - run:
          name: lint
          command: |
            go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.33.0
            go env -w GOPRIVATE=github.com/line/*
            git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
            make lint
workflows:
  version: 2
  test-suite:
    jobs:
      - lint
      - test:
          requires:
            - lint
